# Top-level configuration
name = "cloudflare-worker"
main = "functions/index.mjs"
compatibility_date = "2023-05-18"

routes = [
    "https://cloudflare-bls.pages.dev/*",
    "http:localhost:3000/*",
]
[site]
bucket = "./build" # <-- Add your build directory name here.