# Top-level configuration
name = "cloudflare-worker"
main = "functions/index.js"
compatibility_date = "2023-05-18"

# route = { pattern = "example.org/*", zone_name = "example.org" }

[site]
bucket = "./build" # <-- Add your build directory name here.