name: Push to Another Repository

on:
    push:
        branches:
            - main

jobs:
    push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source repository
              uses: actions/checkout@v2
              with:
                  repository: onattech/cloudflare-public
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Push to target repository
              run: |
                  git remote add target origin https://github.com/onattech/cloudflare-public.git
                  git push target main
